src/app/VoxeetReactComponents.js, src/app/components/ConferencePreConfigContainer.js, src/app/libs/sounds.js, src/app/reducers/ConferenceReducer.js, src/app/reducers/ControlsReducer.js, src/app/reducers/ParticipantsReducer.js
Example:
`import join_sound from './../static/music/voxeet_conference_join.mp3';
import {  ConferenceSounds } from "@voxeet/react-components";
ConferenceSounds.conference_join=join_sound;
`
=> UXKit exports object ConferenceSounds that could be used to customize sounds

src/app/actions/ActiveSpeakerActions.js, src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js, src/app/components/main/Main.js, src/app/index.js
- update to sdk 3.0,
- update authentication flow (using credentials or authentication server),
- extract main component,
- fix few linter issues.
=> Feat/sdk 3.0

src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js
Rename dvcs parameter to dolbyVoice
=> fix: rename dvcs parameter to dolbyVoice

src/app/components/attendees/LoadingScreen.js
=> Don't ignore logo prop in LoadingScreen component

src/app/components/actionsBar/buttons/ToggleAttendeesListButton.js
Fix CCU-75
Wrong number in attendees bottom bar
=> fix: wrong number in attendees bottom bar

src/app/components/attendees/AttendeesParticipantBar.js
Missing modification for quality indicator in participant bar
=> fix: missing modification for quality indicator in participant bar

src/styles/components/AttendeesPresentation.less
=> CCU-85 - CSS modification for file presentation

src/app/actions/ConferenceActions.js
=> CCU-90 your conference is being recorded

src/app/components/attendees/AttendeesChat.js
Prevent scroll down when component update for internal purposes
=> CCU-93 for 3.X

src/app/components/attendees/AttendeesSettings.js
=> Use AttendeesSettingsVuMeter on ipad

src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js, src/app/components/actionsBar/buttons/ToggleAttendeesChatButton.js, src/app/components/actionsBar/buttons/ToggleAttendeesListButton.js, src/app/components/actionsBar/buttons/ToggleMicrophoneButton.js, src/app/components/actionsBar/buttons/TogglePSTN.js, src/app/components/actionsBar/buttons/ToggleRecordingButton.js, src/app/components/actionsBar/buttons/ToggleScreenShareButton.js, src/app/components/actionsBar/buttons/ToggleSettingsButton.js, src/app/components/actionsBar/buttons/ToggleVideoButton.js, src/app/components/attendees/AttendeesSettings.js, src/app/components/preConfig/PreConfigVuMeter.js, src/app/libs/browserDetection.js, src/app/reducers/ConferenceReducer.js, src/app/reducers/ControlsReducer.js
CCU-91 Fix for uxkit
Added helpers for detecting mobile and ios devices. Affects hover property on all buttons and listener mode on ipad
Catch some audio play exceptions
Check is audioContext created in PreConfigVuMeter
=> CCU-91 ipad detection uxkit

src/app/actions/ConferenceActions.js, src/app/languages/localizedStrings.js
Added support for errors: PeerConnectionFailedError, PeerConnectionDisconnectedError, RemoteDescriptionError, CreateAnswerError, ConferenceUninitializedError, PeerDisconnectedError, PeerNotFoundError, ParticipantNotFoundError, ChromeExtensionNotInstalled, BrowserNotSupportedError
=> CCU-86 New error types support 

src/app/components/attendees/modes/Tiles.js
If all remote participants are audio-only, show the avatar tiles as it is today.
If one or more remote participants are sending video, do not show audio-only participant presence in the main layout area, instead only show the video user.
=> CCU-60 show only video users

src/app/components/attendees/AttendeesParticipantVideo.js
AttendeesParticipantVideo component needs to use reference to the stream otherwise track updates won't work
=> CCU-109 camera switching

src/app/actions/ConferenceActions.js, src/app/actions/OnBoardingMessageWithActionActions.js, src/app/actions/OnBoardingMessageWithConfirmationActions.js, src/app/components/ConferenceRoom.js, src/app/components/ConferenceRoomContainer.js, src/app/components/attendees/Attendees.js, src/app/components/attendees/onBoardingMessage/onBoardingMessageWithAction.js, src/app/components/attendees/onBoardingMessage/onBoardingMessageWithConfirmation.js, src/app/languages/localizedStrings.js, src/app/reducers/OnBoardingMessageWithActionReducer.js, src/styles/common/MediaQueries.less, src/styles/components/ConferenceAttendees.less
Added overlay with "Play audio" button that pops up on autoplayBlocked  event; Skip preconfig check for mobile devices and listener only mode
=> CCU-102 allow playing audio button

src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js, src/app/languages/localizedStrings.js
- Added localised strings for error message title and desciription
- Created cases for capacity limit error in ConferenceRoom and ConferenceActions
=> [CCU-117] UXKit implementation of the CCL feature error handling

src/app/components/attendees/Attendees.js, src/app/components/attendees/modes/Tile.js, src/app/components/attendees/modes/Tiles.js
Show tiles for video users only
=> CCU-60 - Show only video participants

src/app/actions/ConferenceActions.js, src/app/components/attendees/AttendeesSettings.js, src/app/components/attendees/modes/Tile.js, src/app/components/attendees/modes/Tiles.js
CCU-142 - VFS request incorrect after changing max stream
CCU-143 - Unwanted video enabling after disabling low bandwidth mode option
Tiles didn't update correctly if one user turns on/off camera in audio only call
=> CCU-142 - CCU-143 Tiles update

src/app/components/attendees/AttendeesSettings.js
Remove persist when audio input is changed
=> CCU-707 Echo in conference

src/app/components/ConferenceRoomContainer.js
Integrate modification from pull request conference permissions was missing for Sidebar
=> CCU-187 integrate modification from client pull request

src/app/components/ConferencePreConfigContainer.js, src/styles/components/ConferenceLoading.less
Turn off "Video enabled" if video device is not accessible
=> Added button "Retry" to retry access to devices in the case of an error

src/app/actions/ConferenceActions.js
Moved session.close() call from after conference leave resolution to conference "left" callback.
=> CCU-217 Fix conference leave and session close race condition

README.md, package.json
=> CCU-218 bump version and readme

src/app/actions/ConferenceActions.js, src/app/actions/ParticipantActions.js, src/app/reducers/ParticipantsReducer.js
Now "streamAdded" event is no longer required to display participant on the list.
Created new event handler for "streamAdded" called onStreamAddedForParticipant.
Simplified logic of onParticipantJoined event handler.
=> CCU-220 Fix participants not visible in conference when no streamAdded event were fired

src/app/actions/ConferenceActions.js, src/app/actions/ParticipantActions.js, src/app/reducers/ParticipantsReducer.js
Reverts voxeet/voxeet-uxkit-react#132
=> Revert "CCU-220 Fix participants not visible in conference when no streamAdded event were fired"

src/app/actions/ConferenceActions.js, src/app/actions/ControlsActions.js, src/app/components/ConferencePreConfigContainer.js, src/app/components/ConferenceRoom.js, src/app/components/attendees/AttendeesSettings.js, src/app/languages/localizedStrings.js, src/app/reducers/ControlsReducer.js
- The switch enables/disables video denoise feature in NDS.
=> Added "Video noise reduction" switch

package.json, src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js, src/app/components/ConferenceRoomContainer.js, src/app/components/actionsBar/buttons/ToggleAttendeesListButton.js, src/app/components/attendees/Attendees.js, src/app/components/attendees/AttendeesList.js, src/app/components/attendees/AttendeesSpatialTracker.js, src/app/components/attendees/MeasuredAttendees.js, src/app/components/attendees/modes/List.js, src/app/components/attendees/modes/ListWidget.js, src/app/components/attendees/modes/Speaker.js, src/app/components/attendees/modes/Speakers.js, src/app/components/attendees/modes/Tile.js, src/app/components/attendees/modes/Tiles.js, src/app/libs/position.js
* CCU-244 Add support for A/V congruence in web UXKit
* CCU-244 Move scene measurement to separate component for better code readability
* CCU-244 Switch to useState when caching participant position
=> Rebase feature/spatial-placement to develop

src/app/actions/ConferenceActions.js, src/app/components/ConferenceRoom.js, src/app/libs/position.js
the spatial audio options was missing from the join options parameters
=> CCU-269 fix spatial audio

src/app/index.js
This commit removed an import - https://github.com/voxeet/voxeet-uxkit-react/commit/98bfe1eacf94e3c310cb794be275c27970129c21#diff-dcfde048a3a3e5386d402332efb309e2b92d78d658d99db14f2a48f1056168a8
=> Add missing compose import

package.json, src/app/actions/ConferenceActions.js, src/app/components/ConferencePreConfigContainer.js, src/app/components/attendees/AttendeesSettings.js, src/app/libs/getVideoDeviceName.js, webpack.config.js, webpack.config.prod.js
- Use SDK 3.7.0 Beta 6
- Add Background Blur for chromium based browsers
=> Add Background Blur capability with SDK 3.7.0 Beta 6

src/app/components/attendees/Attendees.js, src/app/components/attendees/modes/MeasuredTile.js, src/app/components/attendees/modes/SpeakerActive.js, src/app/components/attendees/modes/Speakers.js, src/app/libs/position.js, src/app/reducers/ParticipantsReducer.js
Do not merge yet. 
Still in progress.
=>  fix spatial audio settings issues + code clean up.

src/app/components/ConferencePreConfigContainer.js, src/app/components/ConferenceRoom.js, src/app/components/ConferenceRoomContainer.js, src/app/components/attendees/Attendees.js, src/app/components/attendees/AttendeesSettings.js
Added new property virtualBackgroundModeSupported. It is set to true by default. When it is false, "Bokeh" switch is hidden in the preview screen and in "Settings" tab.
=> CCU-308 Make the visibility of the "Bokeh" switch as configurable

src/app/components/ConferencePreConfigContainer.js, src/app/components/attendees/AttendeesSettings.js
Update VFS limitations to support 49 incoming video streams.
=> CCS-4340 Update VFS limitations to support 49 incoming video streams

src/app/actions/ConferenceActions.js, src/app/components/attendees/chat/MessageList.js, src/styles/components/AttendeesChat.less
CCS-4933 Improved handling of incomming messages to allow different chat message formats
=> CCS-4933 Handle cross-application messages
